### ISSUE TITLE
Is it possible to r/w physical memory by this project?

### ISSUE THREAD

**Issue by buliaoyin** [cocafe/msr-utility#1]
Thanks for this awesome project.  
I use to modify my laptop cpu power limit by intel XTU, but the power limit would be reset by system(may be BIOS) soon. This application can set MSR frequently, exactly what I need.  
But the system also reset MCHBAR register which mapped to physical memory address, will also reset the power limit.  
So I want to known is it possible to access physical memory by this project? THX!

**Comment by cocafe** [comment]
It's nice that this little tool helped you.

Just checked out manual of WinRing0, it did not provided API that could access physics memory.

So, to implement the feature you requested, a library that provides such APIs or a homemade kernel driver is required. That needs some efforts (time) to make it, I'll let you know when it's done.

Or, you're welcomed to fork and implement the feature by yourself.

**Comment by cocafe** [comment]
It looks like WinRing0 can do the job. 

I'll let you know if it's done.

**Comment by buliaoyin** [comment]
Wow, very nice! Thanks again!

**Comment by cocafe** [comment]
Sigh, bad news here...

It seems that winring0 has deprecated features about physical memory. 
Though I manged to enable and re-compile it, just could not get it work.

![image](https://user-images.githubusercontent.com/2220316/44906853-b1616200-ad48-11e8-8f38-7358086a2243.png)

The function fails, and returns corrupted data.

Further, to implement physical memory feature, we need another library or a homemade kernel driver, that surely will need more works.

**Comment by buliaoyin** [comment]
It seems you are right, after some google search, it's unable to access physical memory by winring0 driver.   

And I found this repo may help: https://github.com/vaptu/winio

**Comment by cocafe** [comment]
All right, I'll make a try.

**Comment by cocafe** [comment]
[Debug.zip](https://github.com/cocafe/msr-utility/files/2343067/Debug.zip)

I just pushed the changes, you can review the code.

Due to unsigned WinIO driver, it needs to disable driver signature enforcement to run.

Maybe testing values on something like RWEverything first is a good idea. Anyway, use with cautions.

**Comment by buliaoyin** [comment]
Thanks for your effort. I'll make a try.  
But disable driver signature may not be an option for daily use. 

After I tried RWEverything which was a powerful tool, already got a signature driver which could access direct memory and other ones. [This](https://github.com/Cr4sh/fwexpl) repo used RW's signed driver to do his job, could be an example to walk around the signature issue.

I'm not familiar with coding for Windows, but I'll also try to work on this.

**Comment by cocafe** [comment]
Hmmm...

You can disable signature enforcement in advanced boot menu instead of bcdedit, the 'Test Mode' string will not show on the desktop.

That's looks less painful. ;)

**Comment by buliaoyin** [comment]
By disable signature enforcement in advanced boot menu, the new program works fine.   
But after a normal boot, signature enforcement came back...

**Comment by cocafe** [comment]
Whoa, how about install the winio driver to the system, let it boot with system?

![image](https://user-images.githubusercontent.com/2220316/44957441-50cb5400-af05-11e8-9ef9-ea59b3a4e221.png)

I gonna test this tomorrow.

**Comment by cocafe** [comment]
Not lucky...

I remembered that, by disabling signature check via boot menu and it was able to install some unsigned device drivers, and these devices still worked after reboots.

But installed WinIO driver is unable to load in enforcement enabled boot. :<

**Comment by buliaoyin** [comment]
That's sad...  

It seems to use RW(or other equivalent)‘s signed driver may be the proper option for now.
