### ISSUE TITLE
Question regarding project licensing & attribution 

### ISSUE THREAD

**Issue by alex-spataru** [cocafe/msr-utility#9]
Hi! 

I would like to use part the implementation of `lib/winring0` to manually work with MSRs in an open-source project that I am currently developing (which will be released under the MIT license). Since my project already uses CMake, I found your WinRing0 implementation to be especially useful and easy to integrate with my codebase.

However, as I went through the codebase, I couldn't locate any header or comments specifying the licensing terms or the preferred method of attribution for your project. Could you kindly provide me with guidance on how you would like me to acknowledge the use of your WinRing0 library in my project?

Thanks,
Alex Spataru

**Comment by cocafe** [comment]
Hello. That lib/wingring0 is just a wrapper of importing DLL functions, use as you like. 😉

**Comment by alex-spataru** [comment]
Thank you very much! Closing the issue...
